### ISSUE TITLE
“Stream is closed” Issue

### ISSUE THREAD

**Issue by bigbigwood** [Leibnizhu/spring-boot-starter-netty#1]
Hello 你好，

首先谢谢你提供的这个spring boot和netty的解决方案。 我用了这个解决方案，做了基于netty为servlet容器的 Rest API， 在使用调试过程中，我发现一个很奇怪的现象。如果第一次调用API返回是异常之后，第二次再次调用API，servlet容器那层会返回“**Stream is closed**”的错误。 

**但是这个现象，目前只出现在本机调试，如果放到测试服务器，则不会出现。楼主可以看一下或者分析下原因吗？谢谢！**

**下面是错误信息：**
`2018-02-22 20:17:49.850 ERROR 6524 --- [ecutorGroup-4-1] i.g.l.s.core.RequestDispatcherHandler    : Unexpected exception caught during request

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Stream is closed
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:36)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at com.wofan.water.api.filter.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:27)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.gitlab.leibnizhu.sbnetty.core.NettyFilterChain.doFilter(NettyFilterChain.java:34)
	at io.gitlab.leibnizhu.sbnetty.core.NettyRequestDispatcher.dispatch(NettyRequestDispatcher.java:34)
	at io.gitlab.leibnizhu.sbnetty.core.RequestDispatcherHandler.channelRead0(RequestDispatcherHandler.java:41)
	at io.gitlab.leibnizhu.sbnetty.core.RequestDispatcherHandler.channelRead0(RequestDispatcherHandler.java:18)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:35)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:345)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Stream is closed
	at io.gitlab.leibnizhu.sbnetty.request.HttpRequestInputStream.checkNotClosed(HttpRequestInputStream.java:208)
	at io.gitlab.leibnizhu.sbnetty.request.HttpRequestInputStream.poll(HttpRequestInputStream.java:185)
	at io.gitlab.leibnizhu.sbnetty.request.HttpRequestInputStream.read(HttpRequestInputStream.java:160)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:139)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver$EmptyBodyCheckingHttpInputMessage.<init>(AbstractMessageConverterMethodArgumentResolver.java:324)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:189)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:128)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 51 common frames omitted

2018-02-22 20:17:49.854 ERROR 6524 --- [ecutorGroup-4-1] i.g.l.s.core.RequestDispatcherHandler    : Unexpected exception caught during request

java.lang.IllegalStateException: Stream is closed
	at io.gitlab.leibnizhu.sbnetty.request.HttpRequestInputStream.checkNotClosed(HttpRequestInputStream.java:208)
	at io.gitlab.leibnizhu.sbnetty.request.HttpRequestInputStream.addContent(HttpRequestInputStream.java:37)
	at io.gitlab.leibnizhu.sbnetty.core.ServletContentHandler.channelRead(ServletContentHandler.java:51)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1319)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:904)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by Leibnizhu** [comment]
没遇到过这样的问题, 从表面上来看是因为其他地方关闭了Http请求输入流, 然后又再次读取导致的. 
可能跟应用代码有关, 可以给出你的代码吗?

**Comment by bigbigwood** [comment]
我试图弄一个干净的环境，结果没有出现这问题了，看起来是代码的问题..  是否每次request+response过程，是不是都要调用HttpRequestInputStream.close() 方法一次？

**Comment by bigbigwood** [comment]
@Leibnizhu 我发现下面这段如果被调用了，就正常了。。  想请问下，合适会触发这个ServletContentHandler类的 channelInactive方法？
    
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        inputStream.close();
    }

**Comment by Leibnizhu** [comment]
> 合适会触发这个ServletContentHandler类的 channelInactive方法？

连接断开时, 会触发此回调.  
`inputStream.close();`实际调用的是`HttpRequestInputStream`的`close()`方法,   这个方法把线程安全的`closed`属性设为false, 下次再从输入流读取的时候就会检查`close`属性,发现是false就会报上面你给的这个异常

**Comment by Leibnizhu** [comment]
@bigbigwood 看了下调用栈, 是在`ServletContentHandler`的`channelRead()`方法进入`HttpContent`分支的时候发生的, 这个分支是channel有http请求体输入的时候进入.  
正常来说, 此时channel还是active未断开的状态, `inputStream.close();`此时应该还没有被调用才对, 然而此时 `inputStream.close();`已经被调用, 所以`HttpContent`分支调用`inputStream.addContent()`的时候就会报异常.  
需要找到什么时候有额外调用过close()方法.

**Comment by bedbox** [comment]
hello 支不支持配置spring boot静态网页文件直接访问呢

**Comment by Wsiri** [comment]
你们用的springboot哪个版本呢？

**Comment by Leibnizhu** [comment]
@bedbox 没试过，不过应该支持，这个跟容器关系不大吧。

**Comment by virjar** [comment]
调试出来了，inputstream的close有问题，在keepAlive的情况下，第一次http请求走完，jackson会默认调用一次close。导致连接复用的第二个http请求，读取数据时发生Stream is closed
```
[2024-04-04 11:26:54,362] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
[2024-04-04 11:26:54,362] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> begin springMVC dispatch
```
这里spring框架触发了close
```
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> call inputStream close
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> java.lang.Throwable
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.xxx.service.netty.sbnetty.request.HttpRequestInputStream.close(HttpRequestInputStream.java:115)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at java.base/java.io.PushbackInputStream.close(PushbackInputStream.java:377)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:254)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:369)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4534)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3521)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:274)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:243)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:205)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
[2024-04-04 11:26:54,363] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```
第一次业务处理结束
```
[2024-04-04 11:26:54,373] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> end of springMVC dispatch
```
四秒后，第二次http请求过来
```
[2024-04-04 11:26:58,610] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> begin springMVC dispatch

[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> handleUncaughtException
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> org.springframework.http.converter.HttpMessageNotReadableException: I/O error while reading input message; nested exception is com.xxx.service.netty.sbnetty.request.HttpRequestInputStream$ClientAbortException: Stream is closed
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:217)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
...
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> Caused by: com.xxx.service.netty.sbnetty.request.HttpRequestInputStream$ClientAbortException: Stream is closed
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.xxx.service.netty.sbnetty.request.HttpRequestInputStream.checkNotClosed(HttpRequestInputStream.java:216)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.xxx.service.netty.sbnetty.request.HttpRequestInputStream.poll(HttpRequestInputStream.java:193)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at com.xxx.service.netty.sbnetty.request.HttpRequestInputStream.read(HttpRequestInputStream.java:167)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:82)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:135)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver$EmptyBodyCheckingHttpInputMessage.<init>(AbstractMessageConverterMethodArgumentResolver.java:325)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:194)
[2024-04-04 11:26:58,611] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> 	... 41 more
[2024-04-04 11:26:58,612] sessionId:3e7ab24b-4157-4cc1-9bf0-d1c4fd466ac2 -> end of springMVC dispatch
```

实际上stream close的处理应该只是release buffer，只有channel断开才是真的close
