### ISSUE TITLE
post转的参数没有解析到

### ISSUE THREAD

**Issue by expectation1009** [Leibnizhu/spring-boot-starter-netty#3]
您好!
最近用您这个框架,发现post传的数据没有解析到paramMap中,求解答

**Comment by Leibnizhu** [comment]
的确是没解析。
应该在`NettyHttpServletRequest`类的`parseParameter()`方法中进行解析，目前只使用了`netty`自带的`QueryStringDecoder`类对请求uri进行参数解析，有待加入post请求体的解析

**Comment by Leibnizhu** [comment]
已修复，我本地测了一下没问题，麻烦试下可以没有

**Comment by xinyi486931** [comment]
我刚试了下，可以接收POST参数了 ^_^

**Comment by expectation1009** [comment]
您好！
     我试过了，可以解析post！
还有个错误能帮忙看下吗？
java.lang.IllegalStateException: getWriter has already been called for this response
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.gitlab.leibnizhu.sbnetty.response.NettyHttpServletResponse.getOutputStream(NettyHttpServletResponse.java:315)
	at io.gitlab.leibnizhu.sbnetty.core.RequestDispatcherHandler.channelRead0(RequestDispatcherHandler.java:44)
	at io.gitlab.leibnizhu.sbnetty.core.RequestDispatcherHandler.channelRead0(RequestDispatcherHandler.java:18)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)





------------------ 原始邮件 ------------------
发件人: "xinyi486931"<notifications@github.com>;
发送时间: 2018年8月22日(星期三) 下午3:27
收件人: "Leibnizhu/spring-boot-starter-netty"<spring-boot-starter-netty@noreply.github.com>;
抄送: "爱吃鱼的猫"<2952700177@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Leibnizhu/spring-boot-starter-netty] post转的参数没有解析到 (#3)




我刚试了下，可以接收POST参数了 ^_^

**Comment by Leibnizhu** [comment]
@expectation1009 你是不是调用过`getWriter()`然后又调用`getOutputStream()`?

**Comment by expectation1009** [comment]
我检查下代码




------------------ 原始邮件 ------------------
发件人: "Leibniz.Hu"<notifications@github.com>;
发送时间: 2018年8月22日(星期三) 下午4:00
收件人: "Leibnizhu/spring-boot-starter-netty"<spring-boot-starter-netty@noreply.github.com>;
抄送: "爱吃鱼的猫"<2952700177@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Leibnizhu/spring-boot-starter-netty] post转的参数没有解析到 (#3)




@expectation1009 你是不是调用过getWriter()然后又调用getOutputStream()?

**Comment by Leibnizhu** [comment]
@expectation1009 那这个问题先关闭了。
